apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.annotations.ingressClass }}
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.annotations.scheme }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.ingress.annotations.targetType }}
    alb.ingress.kubernetes.io/backend-protocol: {{ .Values.ingress.annotations.backendProtocol }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: counter-app-tls
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.service.name }}
            port:
              number: {{ .Values.service.port }}
